[build-system] 
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "slideguard"
version = "0.1.0"
requires-python = ">=3.9"

# 🔹 Short description (one line)
description = "A simple and lightweight rate limiter decorator for Python"

# 🔹 Long description (shown on PyPI page)
readme = "README.md"

# 🔹 Optional but important
authors = [
  { name="Mujtaba", email="contact@mujtabaalmas.me" }
]

license = { text = "MIT" }

keywords = ["rate limiter", "python", "decorator", "api", "throttling"]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
include = ["slideguard*"]